language: scala

matrix:
  include:
  - jdk: oraclejdk8
    scala: 2.12.8
  - jdk: oraclejdk8
    scala: 2.11.12
  - jdk: oraclejdk8
    scala: 2.13.0-M5
  - jdk: openjdk11
    scala: 2.12.8
env:
  global:
    secure: GFb3iprmlEb7iy5kA2vCdEMgxMOrWrSPnzLMoU9bCase/5UvNXp0quHzwDlLO9oqj2x+VRBRgJNngYyGB5HU0sRjlvgd2FXAwb5xn3LvGHHJB+j0oVxaYO2DuMeRG9MWuds+IN9EPbmbv36lFHc5NzZZG2ZI9v5+wAJjnCy8QOQ=

before_script: sudo chmod +x /usr/local/bin/sbt # Temporary Fix For https://github.com/travis-ci/travis-ci/issues/7703
script: sbt ++$TRAVIS_SCALA_VERSION validate

cache:
  directories:
  - "$HOME/.ivy2/cache"
  - "$HOME/.sbt/boot"

before_cache:
  - du -h -d 1 $HOME/.ivy2/cache
  - du -h -d 2 $HOME/.sbt/
  - find $HOME/.sbt -name "*.lock" -type f -delete
  - find $HOME/.ivy2/cache -name "ivydata-*.properties" -type f -delete

