language: scala

scala:
  - 2.12.3
  - 2.11.11
  - 2.10.6

jdk:
  - oraclejdk8
env:
  global:
    secure: irOi2r3fey1ecrQOgaTzUredRTY7vafdcBc+nY6eJRtwN/U3qnmgbbXlmj9QIa2mLmWPpumv1nQjHcNS5XMp+Vluu6y1HAv4wPiOs4FCzqNav4yBWt6LFGRmXV/yatgj4Gzm1sFqmJRg80RfNdc5kuvmxpyOnCJAPPSfh6pBH3k=

before_script: sudo chmod +x /usr/local/bin/sbt # Temporary Fix For https://github.com/travis-ci/travis-ci/issues/7703
script: sbt ++$TRAVIS_SCALA_VERSION test

cache:
  directories:
  - "$HOME/.ivy2/cache"
  - "$HOME/.sbt/boot"

before_cache:
  - du -h -d 1 $HOME/.ivy2/cache
  - du -h -d 2 $HOME/.sbt/
  - find $HOME/.sbt -name "*.lock" -type f -delete
  - find $HOME/.ivy2/cache -name "ivydata-*.properties" -type f -delete

jobs:
  include:
    - &publish
      stage: Publish
      scala: 2.12.2-bin-typelevel-4
      script: ./travis-scripts/deploy.sh
    - <<: *publish
      scala: 2.11.11-bin-typelevel-4
      script: ./travis-scripts/deploy.sh
    - <<: *publish
      scala: 2.10.6
      script: ./travis-scripts/deploy.sh

